### PR TITLE
upgrade to v1.10.1

### PR DESCRIPTION
**Pull request by dserodio**

### CODE REVIEW

**Comment by romkatv** [comment]
May I ask why you want this merged? They only difference between v1.10.1 and v1.10.0 is a fix in `build`. This script isn't used in the homebrew package. So this would create upgrade churn for users with no benefits.

**Comment by dserodio** [comment]
I didn't read the changelog, just noticed that there was a more recent version available. Thanks for the quick response.

**Comment by romkatv** [comment]
I own both projects -- the upstream and the homebrew package. You don't need to send PRs that essentially suggest how I should coordinate my own development. It's unlikely that your suggestion will be an improvement simply because I have more context.

**Comment by dserodio** [comment]
Got it, sorry for bothering you

**Pull request closed without merging**
